### PR TITLE
Incorporate improvements from @soshial/@tripplet + myself

### PR DESCRIPTION
**Pull request by ndoo**
Merged a bunch of improvements/fixes from soshial@, and cherry-picked improvements/fixes from tripplet. Added some improvements of my own. Please refer to commits for specifics. Review/feedback welcome.

Duplicates:
* #138
* #141 
* #145 
* #147 
* #148 

Apologies for raising a large PR, but hopefully I was able to add some value, as I have compile-tested and fuctionality-tested the changes on my Freematics ONE+ model B.

### CODE REVIEW

**Review by SpaceCat101 — COMMENTED** [review]
So after changing the volume and frequency (Freematics.cpp), how can I customize it? It sounds the same to me.

**Comment by ndoo** [comment]
> So after changing the volume and frequency (Freematics.cpp), how can I customize it? It sounds the same to me.

Hi there, this is implemented in [51c2548 - telelogger v5: Add customizable startup beep sequence](https://github.com/stanleyhuangyc/Freematics/pull/151/commits/51c2548cc866edd99740442e71f5bcb9833cc961):

The configuration needed is documented in [config.h](https://github.com/stanleyhuangyc/Freematics/pull/151/commits/51c2548cc866edd99740442e71f5bcb9833cc961#diff-472943faa329338b77a21419f3d3b036f5ee3983907325a5f9a9d7ddb9ed41d1):

`#define BEEP_TABLE {2000} /* Hz, each value is a 100ms cycle (use "0" to add gaps) */`

E.g.:

`#define BEEP_TABLE {1000, 0, 2000, 0, 4000} /* Hz, each value is a 100ms cycle (use "0" to add gaps) */`

**Review by SpaceCat101 — COMMENTED** [review]
Hi, 
With this code how are we suppose to control the buzzer? Is the original volume the loudest already?

**Comment by ndoo** [comment]
> Hi, With this code how are we suppose to control the buzzer? Is the original volume the loudest already?

Hi, volume control is out of scope of this PR. The original volume is the loudest possible already.

**Comment by SpaceCat101** [comment]
Hi,
Then what is this PR for? (
[FreematicsPlus: Add buzzer volume control])
Also if that's the case do you have any idea what is the dB of the current volume?

**Comment by SpaceCat101** [comment]
Hi, 
Do you have any clue how I can adjust the volume of the buzzer?

**Comment by PilaScat** [comment]
Is possibile to manually merge this code? Can it work today?

**Comment by ndoo** [comment]
> I wrote to him, in the meantime would you be so kind as to make an updated fork if it's a small thing? Because I have the new 7670 module and the other forks probably wouldn't work

Sorry, it's too much work as the code base has already diverged.

**Pull request closed without merging**
