### PR TITLE
Add buzzer config with default true

### PR DESCRIPTION
**Pull request by gaborgsomogyi**
**Intention:**
I'm basically using the hardware with traccar as security device.
Such case it's good idea to turn off buffer in order to hide it properly.

**What this PR contains:**
In this PR I've added a config to turn off buzzer (default: enabled).

**How it's tested:**
Compiled the code with and without flag and checked the buzzer noise manually.

Since I'm using this hardware every day and found couple of improvement possibilities
I'm intended to fix them in public to help the community to use this device properly.

### CODE REVIEW

**Comment by gaborgsomogyi** [comment]
cc @stanleyhuangyc

**Comment by soshial** [comment]
@stanleyhuangyc, could you please have a look at this PR?

**Comment by gaborgsomogyi** [comment]
@stanleyhuangyc

**Comment by gaborgsomogyi** [comment]
@stanleyhuangyc

**Comment by gaborgsomogyi** [comment]
@stanleyhuangyc

**Pull request closed without merging**
